### ISSUE TITLE
Add "visit" button on the main page

### ISSUE THREAD

**Issue by VForiel** [Dispenser-Projects/Dispenser-Website#1]
When the user is on the main page, he see the block renderer in a little window. It could be great to have a "visit" button next to the "github" one that redirect the user to the dedicated block renderer page
![image](https://user-images.githubusercontent.com/12165342/165505806-00d27f2a-b214-42aa-a602-6cd574c7ddc6.png)

**Comment by Theaustudio** [comment]
fix by [8a7bc53](https://github.com/Dispenser-Projects/Dispenser-Website/commit/8a7bc53ec563334fc98f3cba8e04906ec8c2b2bc)
